doctrine:
    dbal:
        connections:
            default: # Conexión para Security
                url: '%env(resolve:DATABASE_URL)%'
            core: # Conexión para el Negocio
                url: '%env(resolve:DATABASE_CORE_URL)%'
        default_connection: default

        #profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Shared:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared
            Security:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Security/Domain/Entity'
                prefix: 'App\Security\Domain\Entity'
                alias: Security
            Core:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Entity'
                prefix: 'App\Core\Domain\Entity'
                alias: Core
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
